# -*- coding: utf-8 -*-
"""Copy of Food_Delivery_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yd0qLzkN0w2QqI-SyUtEWz7MwPFsjzcg

Import required Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Load Dataset


"""

df=pd.read_csv("/content/food_delivery.csv")
df.head()

"""Check D
ataset Structure

"""

df.info()

"""Check Missing Values"""

df.isnull().sum()

df=df.dropna()

"""Remove Duplicate Records

"""

df.duplicated().sum()
df.drop_duplicates(inplace=True)

"""Check Data Statistics

"""

df.describe()

"""Create new Columns"""

df['Order_Time'] = pd.to_datetime(df['Order_Time'])

#create revenue column
df['Revenue'] = df['Total_Price'] * df['Quantity']

df['Order_Time'].dtype
df['Order_Time']=pd.to_datetime(df['Order_Time'])
df['Order_Time'].dtype

# create order Hour column

df['Hour'] = df['Order_Time'].dt.hour

#create day column
df['Day']=df['Order_Time'].dt.day_name()
df[['Order_Time','Hour','Day']].head()

#create month column
df['Month']=df['Order_Time'].dt.month_name()
df[['Order_Time','Hour','Day','Month']].head()

"""Total orders

"""

total_orders=df['Order_ID'].nunique()
print("Total Orders:",total_orders)

"""Orders by Food Category

"""

df['Item_Name'].value_counts().plot(kind='bar', figsize=(8,5))
plt.title("Orders by Food Category")
plt.xlabel("Food Category")
plt.ylabel("Number of Orders")

plt.show()

"""Orders by Hour(Peak Time Analysis)"""

df['Hour'].value_counts().sort_index().plot(kind='line', marker='o')
plt.title("Orders by Hour")
plt.xlabel("Hour of Day")
plt.ylabel("Number of Orders")
plt.show()

"""Orders by Day

"""

df['Day'].value_counts().plot(kind='bar')
plt.title("Orders by Day")
plt.show()

"""Orders by Month"""

df['Month'].unique()
df['Order_Time'] = pd.to_datetime(df['Order_Time'],errors='coerce')

df['Month'] = df['Order_Time'].dt.month_name()

df['Month'].value_counts().plot(kind='bar')
plt.title("Orders by Month")
plt.show()

"""Revenue Analysis"""

df['Revenue'] = df['Total_Price']*df['Quantity']
print("Total Revenue:",df['Revenue'].sum())

"""Revenue by Restaurant"""

df.groupby('Restaurant_ID')['Revenue'].sum().sort_values(ascending=False).head(10)

"""Revenue by City"""

df.groupby('City')['Revenue'].sum().plot(kind='bar')

plt.title("Revenue by City")

plt.show()

"""Payment method analysis"""

df['Payment_Method'].value_counts().plot(kind='pie', autopct='%1.1f%%')

plt.title("Payment Method Distribution")

plt.show()

"""Delivery Time Analysis"""

df['Delivery_Time'].dtype
df['Delivery_Time'] = pd.to_numeric(df['Delivery_Time'], errors='coerce')
df['Delivery_Time'].dtype
df['Delivery_Time'].head()
df['Delivery_Time'].isnull().sum()
df['Delivery_Time'].unique()

import matplotlib.pyplot as plt

df['Delivery_Duration_Minutes'].plot(kind='hist', bins=20)

plt.title("Delivery Time Distribution")
plt.xlabel("Delivery Duration (Minutes)")
plt.ylabel("Number of Orders")

plt.show()

"""Customer Analysis"""

df.groupby('User_ID')['Revenue'].sum().sort_values(ascending=False).head(10)

"""Corelation Analysis"""

numeric_df=df.select_dtypes(include=['number'])
plt.figure(figsize=(12,8))
sns.heatmap(numeric_df.corr(),annot=True,cmap="coolwarm")
plt.title("Correlation Analysis")
plt.show()

plt.figure(figsize=(12,8))

sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm")

plt.xticks(rotation=45)
plt.yticks(rotation=0)

plt.title("Correlation Analysis")
plt.show()

df.to_csv("food_delivery_cleaned.csv", index=False)

from google.colab import files
files.download("food_delivery_cleaned.csv")

